apiVersion: v1
kind: Pod
metadata:
  name: mongo-db-pod
  namespace: web-app-ns
  labels:
    app: mongo-db
spec:
  containers:
    - name: mongo-db-container
      image: luischacon/mongo-db:latest
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "MyPass1973"
