apiVersion: v1
kind: Pod
metadata:
  name: mongo-db-pod
  namespace: web-app-ns
  labels:
    app: mongo-db
spec:
  containers:
    - name: mongo-db-container
      image: node:lts-alpine3.20
      ports:
        - containerPort: 27017
      env:
        - name: MONGODB_INITDB_ROOT_USERNAME_FILE
          value: "admin"
        - name: MONGODB_INITDB_ROOT_PASSWORD_FILE
          value: "MyPass1973"
