apiVersion: v1
kind: Service
metadata:
  name: mongo-db-service
  namespace: web-app-ns
  labels:
    app: mongo-db
spec:
  selector:
    app: mongo-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
