apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-app-replicaset
  namespace: web-app-ns
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app-container
          image: luischacon/web-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongo-db-service:27017/test"
            - name: NODE_ENV
              value: "development"
